name: test

on:
  push:
    branches:
      - "**"
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["oldstable", "stable"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test with the Go CLI
        run: go test -v -race -count 5 -failfastt
